name: Package OpenResty
on:
  workflow_dispatch:
    inputs:
      alpine-version:
        description: Alpine Linux release version to build for
        default: '3.20'
        required: false
        type: string
  workflow_call:
    inputs:
      alpine-version:
        description: Alpine Linux release version to build for
        default: '3.20'
        required: false
        type: string
      release-version:
        description: Rancher Desktop OpenResty release tag
        required: false
        type: string
permissions: {}
jobs:
  package:
    strategy:
      matrix:
        include:
        - arch: amd64
        - arch: arm64
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ matrix.arch }}
    - uses: docker/setup-buildx-action@v3
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - run: >-
        docker buildx build
        --platform=linux/${{ matrix.arch }}
        --output=type=local,dest=.
        --file=.github/workflows/package.Dockerfile
        --build-arg=RELEASE_VERSION=${{ inputs.release-version }}
        --build-arg=ALPINE_VERSION=${{ inputs.alpine-version }}
        .
    - uses: actions/upload-artifact@v4
      with:
        name: openresty-${{ matrix.arch }}.tar
        path: openresty-*.tar
        if-no-files-found: error
  package-opensuse:
    strategy:
      matrix:
        include:
        - arch: amd64
        - arch: arm64
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ matrix.arch }}
    - uses: docker/setup-buildx-action@v3
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - run: >-
        docker buildx build
        --platform=linux/${{ matrix.arch }}
        --output=type=local,dest=.
        --file=.github/workflows/package-opensuse.Dockerfile
        .
    - run: ls -laR 
    - uses: actions/upload-artifact@v4
      with:
        name: rpms-${{ matrix.arch }}
        path: |
          RPMS/
          SRPMS/
        if-no-files-found: error
  render-opensuse:
    needs: package-opensuse
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
    - run: sudo DEBIAN_FRONTEND=noninteractive apt-get install createrepo-c
    - uses: actions/download-artifact@v4
      with:
        merge-multiple: true
    - run: createrepo_c --no-database .
    - uses: actions/upload-pages-artifact@v3
      with:
        path: .
    - uses: actions/deploy-pages@v4
