name: Package OpenResty
on:
  workflow_dispatch:
    inputs:
      alpine-version:
        description: Alpine Linux release version to build for
        default: '3.20'
        required: false
        type: string
  workflow_call:
    inputs:
      alpine-version:
        description: Alpine Linux release version to build for
        default: '3.20'
        required: false
        type: string
      release-version:
        description: Rancher Desktop OpenResty release tag
        required: false
        type: string
permissions: {}
jobs:
  package:
    strategy:
      matrix:
        include:
        - arch: amd64
        - arch: arm64
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ matrix.arch }}
    - uses: docker/setup-buildx-action@v3
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - run: >-
        docker buildx build
        --platform=linux/${{ matrix.arch }}
        --output=type=local,dest=.
        --file=.github/workflows/package.Dockerfile
        --build-arg=RELEASE_VERSION=${{ inputs.release-version }}
        --build-arg=ALPINE_VERSION=${{ inputs.alpine-version }}
        .
    - uses: actions/upload-artifact@v4
      with:
        name: openresty-${{ matrix.arch }}.tar
        path: openresty-*.tar
        if-no-files-found: error
